# Generated by Django 5.2.4 on 2025-07-29 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('tipo_pessoa', models.CharField(choices=[('Física', 'Física'), ('Jurídica', 'Jurídica')], default='Física', max_length=10)),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CPF', max_length=10)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('dados_bancarios', models.TextField(blank=True, null=True, verbose_name='Dados Bancários')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Fiador',
                'verbose_name_plural': 'Fiadores',
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_imovel', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Sala Comercial', 'Sala Comercial'), ('Terreno', 'Terreno'), ('Galpão', 'Galpão')], max_length=50, verbose_name='Tipo de Imóvel')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço Completo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('status_imovel', models.CharField(choices=[('Disponível', 'Disponível'), ('Alugado', 'Alugado'), ('Vendido', 'Vendido'), ('Em Manutenção', 'Em Manutenção'), ('Inativo', 'Inativo')], default='Disponível', max_length=50, verbose_name='Status do Imóvel')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('area_util', models.PositiveIntegerField(verbose_name='Área Útil (m²)')),
                ('area_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Área Total (m²)')),
                ('andar', models.IntegerField(blank=True, null=True, verbose_name='Andar')),
                ('numero_quartos', models.PositiveIntegerField(default=0, verbose_name='Nº de Quartos')),
                ('numero_banheiros', models.PositiveIntegerField(default=1, verbose_name='Nº de Banheiros')),
                ('vagas_garagem', models.PositiveIntegerField(default=0, verbose_name='Vagas de Garagem')),
                ('codigo_energia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Energia')),
                ('codigo_agua', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Água')),
                ('administradora_condominio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Administradora do Condomínio')),
                ('condominio_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Condomínio')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição do Imóvel')),
                ('data_venda', models.DateField(blank=True, null=True, verbose_name='Data da Venda')),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Aquisição')),
                ('imposto_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Imposto sobre a Venda')),
                ('valor_liquido_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Líquido da Venda')),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Aluguel')),
                ('valor_liquido_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Líquido do Aluguel')),
                ('iptu_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do IPTU')),
                ('seguro_vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento do Seguro')),
                ('seguro_corretora', models.CharField(blank=True, max_length=255, null=True, verbose_name='Corretora do Seguro')),
                ('seguro_seguradora', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seguradora')),
                ('seguro_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Seguro')),
                ('imagens', models.CharField(blank=True, help_text='Caminho ou URL para as imagens', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Intermediario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('tipo_pessoa', models.CharField(choices=[('Física', 'Física'), ('Jurídica', 'Jurídica')], default='Física', max_length=10)),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CPF', max_length=10)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('dados_bancarios', models.TextField(blank=True, null=True, verbose_name='Dados Bancários')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Intermediário',
                'verbose_name_plural': 'Intermediários',
            },
        ),
        migrations.CreateModel(
            name='Locador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('tipo_pessoa', models.CharField(choices=[('Física', 'Física'), ('Jurídica', 'Jurídica')], default='Física', max_length=10)),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CPF', max_length=10)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('dados_bancarios', models.TextField(blank=True, null=True, verbose_name='Dados Bancários')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Locador',
                'verbose_name_plural': 'Locadores',
            },
        ),
        migrations.CreateModel(
            name='Locatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('tipo_pessoa', models.CharField(choices=[('Física', 'Física'), ('Jurídica', 'Jurídica')], default='Física', max_length=10)),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CPF', max_length=10)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('dados_bancarios', models.TextField(blank=True, null=True, verbose_name='Dados Bancários')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Locatário',
                'verbose_name_plural': 'Locatários',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Aluguel (Contratado)')),
                ('valor_deposito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Depósito/Caução')),
                ('status_contrato', models.CharField(choices=[('Ativo', 'Ativo'), ('Encerrado', 'Encerrado'), ('Rescindido', 'Rescindido'), ('Renovado', 'Renovado')], default='Ativo', max_length=20, verbose_name='Status do Contrato')),
                ('data_assinatura', models.DateField(verbose_name='Data da Assinatura')),
                ('data_vencimento_pagamento', models.PositiveIntegerField(verbose_name='Dia do Vencimento do Pagamento')),
                ('multa_rescisoria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Multa Rescisória')),
                ('clausulas_especificas', models.TextField(blank=True, null=True, verbose_name='Cláusulas Específicas')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.imovel', verbose_name='Imóvel')),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.locador', verbose_name='Locador')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.locatario', verbose_name='Locatário')),
            ],
            options={
                'verbose_name': 'Contrato de Locação',
                'verbose_name_plural': 'Contratos de Locação',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('descricao_documento', models.TextField(verbose_name='Descrição do Documento')),
                ('data_documento', models.DateField(verbose_name='Data do Documento')),
                ('arquivo_documento', models.CharField(help_text='Caminho ou URL para o arquivo', max_length=255)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.contrato')),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.imovel')),
                ('locador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.locador')),
                ('locatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.locatario')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField(verbose_name='Data da Solicitação')),
                ('descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('status_manutencao', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20, verbose_name='Status')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('custo_manutencao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo da Manutenção')),
                ('responsavel_manutencao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável/Empresa')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='core.imovel', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(verbose_name='Data do Pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('forma_pagamento', models.CharField(choices=[('Boleto', 'Boleto'), ('Transferência Bancária', 'Transferência Bancária'), ('Cartão de Crédito', 'Cartão de Crédito'), ('PIX', 'PIX')], max_length=50, verbose_name='Forma de Pagamento')),
                ('status_pagamento', models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente'), ('Em Atraso', 'Em Atraso')], default='Pendente', max_length=20, verbose_name='Status')),
                ('multa_juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa/Juros por Atraso')),
                ('comprovante_pagamento', models.CharField(blank=True, help_text='Caminho ou URL para o comprovante', max_length=255, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Pagamento de Aluguel',
                'verbose_name_plural': 'Pagamentos de Aluguel',
            },
        ),
    ]
