# Generated by Django 5.2.4 on 2025-07-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='tipo_garantia',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='data_ultimo_aluguel',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='tipo_garantia',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='valor_venda',
        ),
        migrations.AddField(
            model_name='imovel',
            name='administradora_condominio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Administradora do Condomínio'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='codigo_agua',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Água'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='codigo_energia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Energia'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aquisição do Imóvel'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_venda',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Venda'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='imposto_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Imposto sobre a Venda'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='seguro_corretora',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Corretora do Seguro'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='seguro_seguradora',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seguradora'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='seguro_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Seguro'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='seguro_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento do Seguro'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_aquisicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Aquisição'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_liquido_aluguel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Líquido do Aluguel'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_liquido_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Líquido da Venda'),
        ),
    ]
