# Generated by Django 5.2.4 on 2025-07-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='seguro_corretora',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='seguro_seguradora',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='seguro_valor',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='seguro_vencimento',
        ),
        migrations.AddField(
            model_name='imovel',
            name='avcb_codigo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código AVCB'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='avcb_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Emissão AVCB'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='avcb_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento AVCB'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='vencimento_caixa_dagua',
            field=models.DateField(blank=True, null=True, verbose_name="Vencimento Certificado Caixa d'Água"),
        ),
        migrations.AddField(
            model_name='imovel',
            name='vencimento_dedetizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento da Dedetização'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='vencimento_extintores',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento dos Extintores'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo_imovel',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Sala Comercial', 'Sala Comercial'), ('Prédio Comercial', 'Prédio Comercial'), ('Terreno', 'Terreno'), ('Galpão', 'Galpão')], max_length=50, verbose_name='Tipo de Imóvel'),
        ),
    ]
