# Generated by Django 5.2.4 on 2025-07-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_imovel_seguro_corretora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='seguro_corretora',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Corretora do Seguro'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='seguro_seguradora',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seguradora'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='seguro_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Seguro'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='seguro_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento do Seguro'),
        ),
    ]
